
name: Build and publish WatchBee
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-and-publish-watchbee:
    name: Build and publish WatchBee
    runs-on: ubuntu-slim
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci
        name: Install dependencies

      - run: npm run build:win
        name: Build release for windows

      - name: Create a release.txt
        run: echo ${{ github.sha }} > Release.txt

      - name: Attach releases created
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          # body: |
          #   # New Release of watchbee for VMIX
          #   sha256 : ${{ github.sha }}
          files: |
            Release.txt
            dist/watchbeeforvmix.exe
          token: ${{ secrets.GITHUB_TOKEN }}

