
name: Freeze a release at a given commit, without build
on:
  create:
    tags:
      - "CBP-*.*"
jobs:
  build-and-test:
    name: Run tests and freeze version
    runs-on: ubuntu-slim
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci
        name: Install dependencies

      - run: npm run test:run
        name: Test npm using test suite

  create-release:
    name: Run tests and freeze version
    runs-on: ubuntu-slim
    permissions:
      contents: write
      packages: write
    needs: build-and-test
    steps:

      - name: Create a release.txt
        run: echo ${{ github.sha }} > Release.txt

      - name: Attach releases created
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          body: |
            # New Release of watchbee for VMIX
            sha256 : ${{ github.sha }}
          files: |
            Release.txt
          token: ${{ secrets.GITHUB_TOKEN }}
